# Copyright (C) 2025 Mitsubishi Electric Research Laboratories (MERL)
#
# SPDX-License-Identifier: AGPL-3.0-or-later


name: tuss
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.11.5
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - torchaudio=2.5.1
  - pip
  - pip:
    - pytorch-lightning==2.1.2
    - loguru
    - pyyaml
    - SoundFile==0.12.1
    - tensorboard
    - protobuf==3.20.3
    - fast-bss-eval
    - pesq==0.0.4
    - rotary-embedding-torch==0.6.1
    - numpy==1.26.4
    - librosa
    - matplotlib
    - pandas
    - webrtcvad==2.0.10
